version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: 'rabbitmq'    
    environment:
    - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    ports:
        - 5672:5672
        - 15672:15672       
        - 5552:5552 
        
#version: "3.2"
#services:
#  rabbitmq:
#    image: rabbitmq:3-management    
#    container_name: 'rabbitmq'
#    ports:
#        - 5672:5672
#        - 15672:15672        